version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgresql
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=ldpcom
    restart: always
    volumes:
      - postgresql_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - static_files:/backend/app/static
    ports:
      - "8080"
    depends_on:
      - db
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "80"
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - static_files:/static_files
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
    depends_on:
      - frontend
      - backend
  
volumes:
  postgresql_dev:
  static_files: