version: '3.8'

services:

  db:
    image: postgres:latest
    env_file:
      - ./databases/db.env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  mongodb:
    image: mongo
    env_file:
      - ./databases/mongodb.env
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - static_files:/backend/app/static
    ports:
      - "8443"
    depends_on:
      - db
      - mongodb
  
  webserver:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - static_files:/static_files:ro
      - ./webserver/certbot/www:/var/www/certbot/:ro
      - ./webserver/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    depends_on:
      - backend
  
  certbot:
    image: certbot/certbot:latest
    command: sh -c "certbot renew"
    volumes:
    - ./webserver/certbot/www/:/var/www/certbot/:rw
    - ./webserver/certbot/conf/:/etc/letsencrypt/:rw
  
volumes:
  db:
  mongodb:
  static_files: