version: '3.8'

services:

  db:
    image: postgres:latest
    env_file:
      - ./databases/db.env
    restart: always
    volumes:
      - postgresql_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  mongodb:
    image: mongo
    env_file:
      - ./databases/mongodb.env
    restart: always
    volumes:
      - mongodb_dev:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - static_files:/backend/app/static
    ports:
      - "8080"
    depends_on:
      - db
      - mongodb
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "80"
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - static_files:/static_files
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - frontend
      - backend
  
volumes:
  postgresql_dev:
  mongodb_dev:
  static_files: