"""Article back_populates

Revision ID: 4a8583d3b7ac
Revises: e894d69da0bf
Create Date: 2022-01-26 21:03:03.601769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8583d3b7ac'
down_revision = 'e894d69da0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
