"""is_active on Article

Revision ID: 7424ff553f39
Revises: 4a8583d3b7ac
Create Date: 2022-01-26 23:07:54.506865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7424ff553f39'
down_revision = '4a8583d3b7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_active')
    # ### end Alembic commands ###
